export default {
	TRACKS_LOAD_START: 'TRACKS_LOAD_START',
	TRACKS_LOAD_SUCCESS: 'TRACKS_LOAD_SUCCESS',
	TRACKS_LOAD_ERROR: 'TRACKS_LOAD_ERROR',
	SEARCH_TRACKS_SUCCESS: 'SEARCH_TRACKS_SUCCESS',
	DELETE_SEARCH_TRACKS: 'DELETE_SEARCH_TRACKS',
	ADD_FAVORITES_TRACKS: 'ADD_FAVORITES_TRACKS',
	REMOVE_FAVORITES_TRACKS: 'REMOVE_FAVORITES_TRACKS',
	ADD_TO_PLAYLIST: 'ADD_TO_PLAYLIST',
	REMOVE_ALL_PLAYLIST: 'REMOVE_ALL_PLAYLIST',
	NEXT_TRACK:'NEXT_TRACK',
	PREVIUS_TRACK:'PREVIUS_TRACK'
};
